server:
  port: 8082
  error:
    include-stacktrace: never
  servlet:
    context-path: /api

spring:
  application:
    name: jwt-demo
  datasource:
    username: jwtuser
    password: aFFsaToBgb1PXTrn2xAZHmBBK9zAcTc0
    url: jdbc:postgresql://dpg-cpfmqu7109ks73bnivv0-a.oregon-postgres.render.com/jwt_db_o1fj
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

token:
  secret:
    key: secret-key@123

admin:
  details:
    name: Mohamed Sweelam
    username: msweelam
    password: sweelam123
