server:
  port: 8082
  error:
    include-stacktrace: never
  servlet:
    context-path: /api

spring:
  application:
    name: jwt-demo
  datasource:
      username: jwtuser
      password: letmein
      url: jdbc:postgresql://localhost:5432/jwt-db
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

token:
  secret:
    key: secret-key@123

admin:
  details:
    name: Mohamed Sweelam
    username: msweelam
    password: sweelam123